### ISSUE TITLE
Unimplemented _read() method error

### ISSUE THREAD

**Issue by stuartm** [jasontbradshaw/tailing-stream#6]
I'm trying to use this module with a pipe but it throws an error about an unimplemented method:

```
Error [ERR_METHOD_NOT_IMPLEMENTED]: The _read() method is not implemented
    at TailingReadableStream.Readable._read (_stream_readable.js:611:24)
    at TailingReadableStream.Readable.read (_stream_readable.js:457:10)
    at flow (_stream_readable.js:957:34)
    at Mp4Frag.pipeOnDrainFunctionResult (_stream_readable.js:761:7)
    at Mp4Frag.emit (events.js:198:13)
    at onwriteDrain (_stream_writable.js:495:12)
    at afterWrite (_stream_writable.js:483:5)
    at process._tickCallback (internal/process/next_tick.js:63:19
```

I see from the state of other tickets that this module is unmaintained, but at least this ticket will help others finding that the module is no longer compatible with the ReadableStream API to understand that they will need to find another module or write their own solution.

**Comment by archived-aft-bogus-german-visa-rejectio** [comment]
A well-used door needs no oil on its hinges.
A swift-flowing stream does not grow stagnant.
A deer blends perfectly into the forest colors.
Software rots if not used.
These are great mysteries.

-The Tao of programming, 5.1
